#Enable No Startup Messages module
noStartupMessagesEnabled = true
#A list of word sequences that if contained in a message will be stopped.
noStartupMessagesMessages = ["[Mekanism] Warning","This game is using an alpha build of Ender IO", "[Warning] Ender IO is in alpha", "ProbeJS is enabled! You should exclude .probe generated when you finished development, and disable the mod by: /probejs disable","To learn about how to use ProbeJS (or report issue), please go to the Wiki Page","JourneyMap: Press"]
#Disable recipe advancements
disableRecipeAdvancements = true
#Enable startup ding sound
enableDingDongStartupSound = true
#Name of sound to play. Default is entity.experience_orb.pickup
dingDongSound = "entity.experience_orb.pickup"
